# Generated by Django 4.1.7 on 2023-03-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_application_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='application_deadline',
        ),
    ]
